[package]
name = "itoa"
version = "0.4.4" # remember to update html_root_url
authors = ["David Tolnay <dtolnay@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "Fast functions for printing integer primitives to an io::Write"
repository = "https://github.com/dtolnay/itoa"
documentation = "https://github.com/dtolnay/itoa"
categories = ["value-formatting"]
readme = "README.md"
exclude = ["performance.png", "/sgx/*"]

[features]
default = ["std", "mesalock_sgx"]
i128 = []
std = []

# Supports rust-sgx-sdk using cargo and xargo
mesalock_sgx = ["sgx_tstd"]

[badges]
travis-ci = { repository = "dtolnay/itoa" }

[target.'cfg(not(target_env = "sgx"))'.dependencies]
sgx_tstd = { rev = "v1.0.9", git = "https://github.com/baidu/rust-sgx-sdk.git", optional = true }
